
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj8OQqv8j7WXdzyhwPheHkmbBn6Dgiq1I',
    authDomain: 'simplechat2-2be15.firebaseapp.com',
    projectId: 'simplechat2-2be15',
    storageBucket: 'simplechat2-2be15.appspot.com',
    messagingSenderId: '585646070681',
    appId: '1:585646070681:web:af6b25a1e5e9ce1efa5108'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrT4doQFtlkfXG8dp3DNttO0K3pNxbg0Q',
    appId: '1:585646070681:android:0123e030e592bba8fa5108',
    messagingSenderId: '585646070681',
    projectId: 'simplechat2-2be15',
    storageBucket: 'simplechat2-2be15.appspot.com'
  );
}
